development: 
  cloud_name: "jebitok"
  api_key: "835369299224749"
  api_secret: "9PFZfrDNqxnlwrR5fiyaE2OuyGc"
  secure: true

production:
  cloud_name: "jebitok"
  api_key: "835369299224749"
  api_secret: "9PFZfrDNqxnlwrR5fiyaE2OuyGc"
  secure:true
  